# Gunakan base image yang ringan dan kompatibel
FROM node:18-bullseye

# Set working directory di dalam container
WORKDIR /app

# Salin file package.json dan package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Instal dependencies tambahan untuk Puppeteer
RUN apt-get update && apt-get install -y \
  libnss3 \
  libatk1.0-0 \
  libx11-xcb1 \
  libxcb-dri3-0 \
  libxcomposite1 \
  libxdamage1 \
  libxrandr2 \
  libgbm1 \
  libasound2 \
  libpangocairo-1.0-0 \
  libpango-1.0-0 \
  libcairo2 \
  libatk-bridge2.0-0 \
  libcups2 \
  && rm -rf /var/lib/apt/lists/*

# Salin semua file proyek
COPY . .

# Expose port aplikasi (sesuai dengan yang digunakan di server.js)
EXPOSE 3000

# Perintah untuk menjalankan aplikasi
CMD ["node", "server.js"]
